version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Jyotchat-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/backend/output.txt
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Jyotchat-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=https://jyotchat.azurewebsites.net
      - NEXT_PUBLIC_CHAT_API=https://jyotchat.azurewebsites.net/api/chat
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
