version: '3.8'

services:
  proxy:
    image: jyotchat.azurecr.io/jyotchatproxy:build-1
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    image: jyotchat.azurecr.io/jyotchatbackend:build-1
    container_name: Jyotchat-backend
    environment:
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

    networks:
      - app-network

  frontend:
    image: jyotchat.azurecr.io/jyotchatfrontend:build-1
    container_name: Jyotchat-frontend
    environment:
      - NEXT_PUBLIC_BASE_URL=https://jyotchat.azurewebsites.net
      - NEXT_PUBLIC_CHAT_API=https://jyotchat.azurewebsites.net/api/chat
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
