version: '3.8'

services:
  proxy:
    image: jyotchat.azurecr.io/jyotchatproxy:build-1
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    image: jyotchat.azurecr.io/jyotchatbackend:build-1
    container_name: Jyotchat-backend
    environment:
      - AZURE_SPEECH_KEY=a1c5d84409ac40a2ab4b06ce4d0bb6b7
      - COHERE_API_KEY=zQ39yHSCDroaW26d39wC87TJkcHyC0o4ky1P5th5
      - OPENAI_API_KEY=sk-ai-engineering-jyot-stl-Db4NPPc1reUDPeGOS22kT3BlbkFJmdLox0TwBNr2eR0dpTKq
      - PINECONE_API_KEY=83c5e56e-aaa2-4d6d-ac69-ca04e632d8c3
      - PINECONE_INDEX_NAME=jyot
      - DB_USER=postgres.rqrqwmvhoppmopkjaarg
      - DB_PASS=2r97x94P2kdYupc2
    networks:
      - app-network

  frontend:
    image: jyotchat.azurecr.io/jyotchatfrontend:build-1
    container_name: Jyotchat-frontend
    environment:
      - NEXT_PUBLIC_BASE_URL=https://jyotchat.azurewebsites.net
      - NEXT_PUBLIC_CHAT_API=https://jyotchat.azurewebsites.net/api/chat
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
